#!/bin/bash

case $1 in
    start)
        echo "Starting..."
        ;;
    restart)
        echo "Restarting..."
        ;;
    stop)
        echo "Stopping..."
        ;;
    *)
        echo "Doing default thing..."
        ;;
esac

